---
output:
  pdf_document:
    number_sections: yes
    fig_caption: yes
    toc: true
    toc_depth: 3
  word_document: default
fontsize: 10.5pt
header-includes:
- \usepackage{fancyhdr}
- \pagestyle{fancy}
- \fancyhead[R]{Group 1}
- \usepackage{float}
bibliography: thebib.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, tidy = TRUE,tidy.opts=list(width.cutoff= 70), fig.pos = "!h")
```

```{r  include=FALSE, message=FALSE}
# Input Data and library
library(tidyverse)
library("here")
library(formattable)
library(leaps)
alldata <- read.csv(here::here("data","counties.csv"), header=T) 
attach(alldata)
Physician_rate <- alldata$Active.Physicians.per.100000.Population.2018..AAMC.
Specialist <- alldata$All.Specialties..AAMC.
ElderlyRate <- alldata$Pop_Above_65
Poverty <- POVALL_2018
Migration <- INTERNATIONAL_MIG_2018
Nurse <- Total.nurse.practitioners..2019.
Covid19 <- data.frame(Mortality, ElderlyRate, Region, Specialist, population, Physician_rate, Unemployment_rate_2018, Poverty, Migration, Nurse)
```

\pagebreak

# Abstract

# Introduction

# Dataset Description (Diga - you made some changes! -> save -> committee -> push)

# investigation: single model fitting -> significant 

# Model Selection 

```{r}
f <- regsubsets(Mortality~., data=Covid19,nbest=2, nvmax=7)
e <- summary(f)
attach(e)
cbind(which,cp,adjr2)
```

# Assumption Checking (Diga)

# Results

# Limitation of Study 

# Conclusion 

\pagebreak

# Appendix{-}

# Reference {-}

\pagebreak

# R Code {-}


